[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
author = "Ciencia de Datos • GECI"
author-email = "ciencia.datos@islas.org.mx"
classifiers = [ "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",]
home-page = "https://github.com/IslasGECI/seabird_sampling"
requires = [
    "distdens @ git+https://git@github.com/IslasGECI/distdens.git",
    "fastkml",
    "geci-test-tools",
    "scikit-learn-stubs",
    "scikit-learn",
    "scipy-stubs",
]
module = "seabird_sampling"
requires-python=">=3.10"

[tool.flit.scripts]
muestreo-aves-marinas-ipbc = "seabird_sampling.cli:cli"
seabird-sampling = "seabird_sampling.cli:cli"

[[tool.mypy.overrides]]
module = [
    "distdens.models",
    "distdens",
    "geci_plots",
    "geci_test_tools",
    "geoambiental.io",
    "geoambiental",
    "utm",
]
ignore_missing_imports = true

[tool.mutmut]
paths_to_mutate = [ "seabird_sampling/" ]

