[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
author = "Ciencia de Datos • GECI"
author-email = "ciencia.datos@islas.org.mx"
classifiers = [ "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",]
home-page = "https://bitbucket.org/IslasGECI/muestreo-aves-marinas-ipbc"
requires = [
    "population-trend==5.*",
    "scikit-learn",
]
module = "muestreo_aves_marinas_ipbc"
requires-python=">=3.10"

[tool.flit.scripts]
muestreo-aves-marinas-ipbc = "muestreo_aves_marinas_ipbc.cli:cli"
